# Generated by Django 3.1 on 2020-08-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
