# Generated by Django 3.1 on 2020-08-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0002_auto_20200818_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'combination',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('essay', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionApp.applicant')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionApp.combination')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
